Added more settings for vim ale for php development

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,7 +5,7 @@ jobs:
     # machine: true
     docker:
       # - image: circleci/golang:1.12.12-buster
-      - image: mandy91/dotfiles-build:0.1
+      - image: mandy91/dotfiles-build:0.1.1
     steps:
       - checkout
       - setup_remote_docker #:
@@ -93,3 +93,16 @@ jobs:
               fi
             done <<<$(git ls-files -- '*.desktop')
             exit $failed
+
+      - run:
+          name: Markdownlint
+          when: always
+          command: |
+            set +e
+            failed=0
+            while read -r file; do
+              if ! markdownlint "$file"; then
+                failed=1
+              fi
+            done <<<$(git ls-files -- '*.md')
+            #exit $failed
